application: hello-django-app-engine
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: myproject.wsgi.application
- url: /myproject/templates/hello
  static_dir: /myproject/templates/hello

libraries:
- name: django
  version: 1.5
- name: numpy
  version: 1.6.1
